services:
  frontend:
    image: nginx:alpine
    container_name: nginx_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    image: 127.0.0.1:5000/app
    build: ./backend   
    container_name: flask_backend
    command: gunicorn -b 0.0.0.0:5000 app:app  
    environment:
      - DATABASE_URL=postgresql://user:1234@db:5432/names_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17.6-bookworm
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=names_db
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: